name: comarques
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^2.0.2+1

dev_dependencies:
  pedantic: ^1.0.2
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/